import java.util.*

val präpositionsFälle = mapOf<String, EnumSet<Kasus>>(
    // Präpositionen Genitiv
    "angesichts" to EnumSet.of(Kasus.Genitiv),
    "anhand" to EnumSet.of(Kasus.Genitiv),
    "anlässlich" to EnumSet.of(Kasus.Genitiv),
    "anstatt" to EnumSet.of(Kasus.Genitiv),
    "anstelle" to EnumSet.of(Kasus.Genitiv),
    "aufgrund" to EnumSet.of(Kasus.Genitiv),
    "außerhalb" to EnumSet.of(Kasus.Genitiv),
    "beiderseits" to EnumSet.of(Kasus.Genitiv),
    "bezüglich" to EnumSet.of(Kasus.Genitiv),
    "diesseits" to EnumSet.of(Kasus.Genitiv),
    "infolge" to EnumSet.of(Kasus.Genitiv),
    "innerhalb" to EnumSet.of(Kasus.Genitiv),
    "jenseits" to EnumSet.of(Kasus.Genitiv),
    "längs" to EnumSet.of(Kasus.Genitiv),
    "links" to EnumSet.of(Kasus.Genitiv),
    "mithilfe" to EnumSet.of(Kasus.Genitiv),
    "oberhalb" to EnumSet.of(Kasus.Genitiv),
    "rechts" to EnumSet.of(Kasus.Genitiv),
    "unterhalb" to EnumSet.of(Kasus.Genitiv),
    "statt" to EnumSet.of(Kasus.Genitiv),
    "südlich" to EnumSet.of(Kasus.Genitiv),
    "trotz" to EnumSet.of(Kasus.Genitiv),
    "ungeachtet" to EnumSet.of(Kasus.Genitiv),
    "unweit" to EnumSet.of(Kasus.Genitiv),
    "während" to EnumSet.of(Kasus.Genitiv),
    "wegen" to EnumSet.of(Kasus.Genitiv),
    "westlich" to EnumSet.of(Kasus.Genitiv),

    // Präpositionen Dativ
    "aus" to EnumSet.of(Kasus.Dativ),
    "außer" to EnumSet.of(Kasus.Dativ),
    "bei" to EnumSet.of(Kasus.Dativ),
    "binnen" to EnumSet.of(Kasus.Dativ),
    "entgegen" to EnumSet.of(Kasus.Dativ),
    "entsprechend" to EnumSet.of(Kasus.Dativ),
    "gegenüber" to EnumSet.of(Kasus.Dativ),
    "gemäß" to EnumSet.of(Kasus.Dativ),
    "mit" to EnumSet.of(Kasus.Dativ),
    "nach" to EnumSet.of(Kasus.Dativ),
    "nahe" to EnumSet.of(Kasus.Dativ),
    "samt" to EnumSet.of(Kasus.Dativ),
    "seit" to EnumSet.of(Kasus.Dativ),
    "von" to EnumSet.of(Kasus.Dativ),
    "zu" to EnumSet.of(Kasus.Dativ),
    "zufolge" to EnumSet.of(Kasus.Dativ),
    "zuliebe" to EnumSet.of(Kasus.Dativ),

    // Präpositionen Akkusativ
    "für" to EnumSet.of(Kasus.Akkusativ),
    "um" to EnumSet.of(Kasus.Akkusativ),
    "durch" to EnumSet.of(Kasus.Akkusativ),
    "entlang" to EnumSet.of(Kasus.Akkusativ),
    "gegen" to EnumSet.of(Kasus.Akkusativ),
    "ohne" to EnumSet.of(Kasus.Akkusativ),
    "wider" to EnumSet.of(Kasus.Akkusativ),

    // Präpositionen Dativ + Akkusativ
    "an" to EnumSet.of(Kasus.Dativ, Kasus.Akkusativ),
    "auf" to EnumSet.of(Kasus.Dativ, Kasus.Akkusativ),
    "hinter" to EnumSet.of(Kasus.Dativ, Kasus.Akkusativ),
    "in" to EnumSet.of(Kasus.Dativ, Kasus.Akkusativ),
    "neben" to EnumSet.of(Kasus.Dativ, Kasus.Akkusativ),
    "über" to EnumSet.of(Kasus.Dativ, Kasus.Akkusativ),
    "unter" to EnumSet.of(Kasus.Dativ, Kasus.Akkusativ),
    "vor" to EnumSet.of(Kasus.Dativ, Kasus.Akkusativ),
    "zwischen" to EnumSet.of(Kasus.Dativ, Kasus.Akkusativ),
    "an" to EnumSet.of(Kasus.Dativ, Kasus.Akkusativ)
)